default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/autosave_development.sqlite3

test:
  <<: *default
  database: db/autosave_test.sqlite3

production:
  <<: *default
  database: db/autosave_production.sqlite3
